language: node_js
sudo: required
node_js:
  - "9"
env:
  global:
    - secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
    - DOCKER_FOLDER: "https://github.com/openworm/org.geppetto.git#feature/35:utilities/docker/geppetto/"
    - IMAGE_NAME: geppetto
    - CONTAINER_NAME: geppetto_container
    - DEFAULT_BRANCH: development
    - LANDING_PAGE: "http://localhost:8080/org.geppetto.frontend"
services:
  - docker
install:
  - npm install jest@24.8.0 puppeteer@1.17.0 jest-puppeteer@4.3.0 babel-preset-env@1.6.0 url-join@4.0.0
script:
  - travis_retry docker build -t=$IMAGE_NAME --build-arg targetBranch=$TRAVIS_BRANCH --build-arg originBranch=$TRAVIS_PULL_REQUEST_BRANCH --build-arg defaultBranch=$DEFAULT_BRANCH $DOCKER_FOLDER
  - travis_retry docker run  -t -dit --name=$CONTAINER_NAME -p 8080:8080 $IMAGE_NAME
  - bash $TRAVIS_BUILD_DIR/tests/casperjs/utilities/test_geppetto_server.sh
  - sleep 30
  - http_status=$(curl -s -I $1 $LANDING_PAGE | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status"
  - while [ "$http_status" == "404" ]; do
      echo "Restart run. Printing logs for debugging purposes";
      sudo docker cp $CONTAINER_NAME:/home/developer/virgo/serviceability/logs/log.log /etc;
      tail -n 200 /etc/log.log;
      docker stop $(docker ps -a -q);
      sleep 10;
      docker rm $(docker ps -a -q);
      sleep 10;
      travis_retry docker run  -t -dit --name=$CONTAINER_NAME -p 8080:8080 $IMAGE_NAME;
      bash $TRAVIS_BUILD_DIR/tests/casperjs/utilities/test_geppetto_server.sh;
      sleep 60;
      http_status=$(curl -s -I $1 $LANDING_PAGE | grep HTTP/1.1 | awk {'print $2'});
      echo "Done restarting $http_status";
    done;
  - travis_wait 35 travis_retry npm run test-in-sequence --verbose --colors
  - docker ps -a;
  - sudo docker cp $CONTAINER_NAME:/home/developer/virgo/serviceability/logs/log.log /etc
  - tail /etc/log.log -n 200
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
