name: Geppetto Application Workflow

on:
  push:
  pull_request:
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy the local and remote versions of geppetto-vfb
  deploy-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # total job timeout:
    timeout-minutes: 60

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses : actions/checkout@v2.3.4    
      - name: Set global bariable with current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: git_branch
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push local wss
        id: docker_build_local
        timeout-minutes: 15
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "geppetto/geppetto-application:${{ steps.git_branch.outputs.branch }}"
          build-args: |
            targetBranch=${{ steps.git_branch.outputs.branch }}
            originBranch=${{ steps.git_branch.outputs.branch }}
            defaultBranch=development
      
      - name: Image digest
        run: |
          echo "local:${{ steps.docker_build_local.outputs.digest }}"
          echo "remote:${{ steps.docker_build_remote.outputs.digest }}"
                
      - name: Install Puppeteer
        run: npm install jest@24.8.0 jest-image-snapshot@4.1.0 puppeteer@1.17.0 jest-puppeteer@4.3.0 @babel/preset-env@7.4.5 url-join@4.0.0 @babel/core@7.4.5
      - name: Start Geppetto
        run: docker run -t -dit --name=geppetto_container  -p 8080:8080 "geppetto/geppetto-application:${{ steps.git_branch.outputs.branch }}";
      - name: Wait for Geppetto Server to be up
        run: |  
          export LANDING_PAGE="http://localhost:8080/org.geppetto.frontend/geppetto"  
          Test () { export http_status=$(curl -s -i $LANDING_PAGE | grep HTTP/1.1 | awk {'print $2'}); echo "Returned status \"$http_status\""; if [ "$http_status" != "200" ]; then echo "Waiting for docker to finish building..."; iterations=$((iterations+1)); if [ "$iterations" != "100" ]; then sleep 1; Test; fi; else echo "$(date) - connected successfully"; fi; }
          Test;
      - name: Run Tests
        continue-on-error: true
        run: npm test -- --verbose --colors
      - name: Stop VFB server   
        run: docker stop geppetto_container